In [30]:
import numpy as np

In [39]:
v1 = np.arange(1,11,1)
m1 = np.arange(1,11,1).reshape(-1,2)
print(f"{v1} \n \n {m1}")

[ 1  2  3  4  5  6  7  8  9 10] 
 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [32]:
v2 = np.arange(11,21,1)
m2 = np.arange(11,21,1).reshape(-1,2)
print(f"{v2} \n \n {m2}")

[11 12 13 14 15 16 17 18 19 20] 
 
 [[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [33]:
producto_punto = np.dot(v1, v2)
print('Producto punto:', producto_punto)

Producto punto: 935


In [34]:
norma = np.linalg.norm(v1)
print('Norma del vector:', norma)

Norma del vector: 19.621416870348583


In [35]:
prod = v1@v2
print('Prducto de dos vectores:', prod)

Prducto de dos vectores: 935


In [41]:
prod = m1@m2.T
print('Prducto de dos matrices: \n', prod)

Prducto de dos matrices: 
 [[ 35  41  47  53  59]
 [ 81  95 109 123 137]
 [127 149 171 193 215]
 [173 203 233 263 293]
 [219 257 295 333 371]]


In [42]:
media = np.mean(v1)
mediana = np.median(2)
print('Media:', media)
print('Mediana:', mediana)

Media: 5.5
Mediana: 2.0
